# Generated by Django 5.2.5 on 2025-10-20 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeometryLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField()),
                ('level', models.CharField(max_length=30)),
                ('shape_focus', models.CharField(blank=True, max_length=50)),
                ('materials', models.TextField(blank=True)),
                ('steps', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='geometry/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeometryExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='geometry.geometrylesson')),
            ],
        ),
    ]
