# Generated by Django 5.2.5 on 2025-10-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geometry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geometrylesson',
            name='emoji',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='geometrylesson',
            name='theory',
            field=models.TextField(blank=True),
        ),
    ]
