# Generated by Django 5.2.5 on 2025-08-14 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0002_alter_exercise_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва завдання')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-псевдонім')),
                ('instructions', models.TextField(verbose_name='Інструкція')),
                ('level', models.CharField(blank=True, max_length=50, verbose_name='Рівень')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Тривалість (хв)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tasks/', verbose_name='Зображення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='lessons.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Завдання',
                'verbose_name_plural': 'Завдання',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
