# Generated by Django 5.2.5 on 2025-08-13 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Наприклад, 'Світло і тінь'", max_length=200, verbose_name='Назва уроку')),
                ('slug', models.SlugField(help_text="Коротка назва для адреси сторінки, наприклад, 'svitlo-i-tin'", max_length=200, unique=True, verbose_name='URL-псевдонім')),
                ('description', models.TextField(verbose_name='Короткий опис')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва вправи')),
                ('content', models.TextField(verbose_name='Текст вправи або інструкція')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок відображення')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='lessons.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Вправа',
                'verbose_name_plural': 'Вправи',
                'ordering': ['order'],
            },
        ),
    ]
