# Generated by Django 5.2.5 on 2025-08-14 08:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Вправа', 'verbose_name_plural': 'Вправи'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['created_at', 'id'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='content',
        ),
        migrations.AddField(
            model_name='exercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Створено'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(blank=True, max_length=50, verbose_name='Складність'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Тривалість (хв)'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='hints',
            field=models.TextField(blank=True, verbose_name='Підказки'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='instructions',
            field=models.TextField(blank=True, verbose_name='Інструкції'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='slug',
            field=models.SlugField(default='temp-slug', unique=True, verbose_name='URL-псевдонім'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='age_range',
            field=models.CharField(blank=True, help_text="Напр., '5–7 років'", max_length=50, verbose_name='Вік учнів'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Тривалість (хв)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='emoji',
            field=models.CharField(blank=True, help_text='Напр., 🔦', max_length=10, verbose_name='Емодзі'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='level',
            field=models.CharField(blank=True, help_text="Напр., '1 клас', 'легкий', 'середній'", max_length=50, verbose_name='Рівень'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='materials',
            field=models.TextField(blank=True, help_text="Напр., 'ліхтарик, м’ячик, зірочка...'", verbose_name='Матеріали'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='safety_note',
            field=models.TextField(blank=True, verbose_name='Примітка з безпеки'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='steps',
            field=models.TextField(blank=True, help_text='Що робити поетапно (один крок на рядок)', verbose_name='Кроки'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='lessons.lesson'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(help_text='Що будемо досліджувати в цьому уроці?', verbose_name='Короткий опис'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(help_text="Коротка назва в адресі, напр., 'svitlo-i-tin'", max_length=200, unique=True, verbose_name='URL-псевдонім'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(help_text="Напр., 'Світло і тінь'", max_length=200, verbose_name='Назва уроку'),
        ),
    ]
