# Generated by Django 5.2.5 on 2025-08-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_exercise_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='assistant_image',
            field=models.CharField(default='assistant_girl.png', max_length=100, verbose_name='Файл зображення асистента'),
        ),
    ]
