# Generated by Django 5.2.5 on 2025-08-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lesson_assistant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='assistant_image',
            field=models.CharField(choices=[('images/assistant_girl.png', 'Дівчинка'), ('images/assistant_boy.png', 'Хлопчик')], default='images/assistant_girl.png', max_length=100, verbose_name='Помічник'),
        ),
    ]
