# Generated by Django 5.2.5 on 2025-08-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_lesson_assistant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
