# Generated by Django 5.2.5 on 2025-08-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_exercise_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Короткий опис'),
        ),
    ]
