# Generated by Django 5.2.5 on 2025-08-16 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_lesson_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-created_at'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='hints',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='safety_note',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Легко'), ('medium', 'Середньо'), ('hard', 'Важко')], help_text='Складність вправи', max_length=50),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Тривалість (у хвилинах)'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Порядок у уроці'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='age_range',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Вік'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='assistant_image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Зображення асистента'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='emoji',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Емоджі'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Рівень складності'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='materials',
            field=models.TextField(blank=True, null=True, verbose_name='Матеріали'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='steps',
            field=models.TextField(blank=True, null=True, verbose_name='Кроки'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Назва уроку'),
        ),
    ]
