# Generated by Django 5.2.5 on 2025-08-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_alter_exercise_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='theory',
            field=models.TextField(blank=True, help_text='Текстовий опис для пояснення теорії'),
        ),
    ]
