# Generated by Django 5.2.5 on 2025-09-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_alter_lesson_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='parent_notes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
