# Generated by Django 5.2.5 on 2025-09-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_lesson_parent_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='safety_note',
            field=models.TextField(blank=True, null=True, verbose_name='Примітка з безпеки'),
        ),
    ]
