# Generated by Django 5.2.5 on 2025-09-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_lesson_safety_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Опубліковано'),
        ),
    ]
